/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_netease_util_InodeUtil */

#ifndef _Included_com_netease_util_InodeUtil
#define _Included_com_netease_util_InodeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_netease_util_InodeUtil
 * Method:    getInode
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_netease_util_InodeUtil_getInode
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
